"""
content_agent.py
================
Content creation and publishing agent.
Automates blog posts, ebooks, and social-media content generation,
along with publishing to Medium and Substack.
"""
from __future__ import annotations

import random
import time
import uuid
from typing import Any, Dict

from money_engine.base_agent import BaseMoneyAgent, AgentDecision
from money_engine.orchestrator import register_agent


@register_agent
class ContentAgent(BaseMoneyAgent):
    """
    Money-making agent focused on content creation and publishing.

    Revenue model (simulated):
      - Blog post generated    : $0.50
      - E-book generated       : $5.00
      - Social post generated  : $0.10
      - Publish to Medium      : $0.25 (simulated ad-revenue share)
      - Publish to Substack    : $0.25
      - Screenshot review      : $0.00
    """

    VERTICAL: str = "content"

    # Simulated revenue per action type
    _REVENUE_TABLE: Dict[str, float] = {
        "generate_blog": 0.50,
        "generate_ebook": 5.00,
        "generate_social": 0.10,
        "publish_to_medium": 0.25,
        "publish_to_substack": 0.25,
        "screenshot_review": 0.00,
    }

    def decide(self) -> AgentDecision:
        """
        Choose the next content action based on simple state heuristics.

        Prefers generation when the ledger is light, and publishing when
        content has been generated recently. Falls back to random choice.
        """
        possible = [
            "generate_blog",
            "generate_ebook",
            "generate_social",
            "publish_to_medium",
            "publish_to_substack",
            "screenshot_review",
        ]

        # Heuristic: if we have made very few decisions, bias toward generation
        if self.state.decisions_made < 3:
            weights = [0.40, 0.30, 0.20, 0.03, 0.03, 0.04]
        else:
            # Check recent ledger for generation vs publish
            recent_generations = sum(
                1
                for entry in self.state.ledger[-5:]
                if entry.get("action", "").startswith("generate_")
            )
            if recent_generations >= 3:
                # We have content; bias toward publishing or review
                weights = [0.05, 0.05, 0.05, 0.30, 0.30, 0.25]
            else:
                # Need more content
                weights = [0.35, 0.25, 0.20, 0.07, 0.07, 0.06]

        action = random.choices(possible, weights=weights, k=1)[0]

        params: Dict[str, Any] = {}
        if action == "generate_blog":
            params = {
                "topic": random.choice(
                    [
                        "passive income strategies",
                        "AI side hustles",
                        "freelance writing tips",
                        "remote work productivity",
                    ]
                ),
                "keywords": ["ai", "automation", "side hustle"],
                "tone": "professional",
                "length": "medium",
            }
        elif action == "generate_ebook":
            params = {
                "topic": random.choice(
                    [
                        "The Solo Founder Playbook",
                        "Zero to $1K MRR",
                        "Automate Your Income",
                    ]
                ),
                "chapters": 5,
            }
        elif action == "generate_social":
            params = {
                "topic": random.choice(
                    [
                        "3 mistakes that kill startups",
                        "The 1 habit of every 6-figure creator",
                        "Why your offer isn't selling",
                    ]
                ),
                "tweets": 5,
            }
        elif action in ("publish_to_medium", "publish_to_substack"):
            params = {
                "title": f"Auto-generated post {uuid.uuid4().hex[:4]}",
                "body": "This is automated content generated by the ContentAgent.",
            }
        elif action == "screenshot_review":
            params = {"reason": "Visual verification of current browser state"}

        return AgentDecision(
            decision_id=f"content_{uuid.uuid4().hex[:8]}",
            timestamp=time.time(),
            action=action,
            params=params,
            reasoning=f"Selected '{action}' based on heuristic weights and recent ledger.",
        )

    def execute(self, decision: AgentDecision) -> dict:
        """
        Execute the chosen content action.

        Args:
            decision: The AgentDecision produced by decide().

        Returns:
            A dict with at minimum ``success`` and ``revenue`` keys.
        """
        action = decision.action
        params = decision.params
        revenue = self._REVENUE_TABLE.get(action, 0.0)

        if action == "generate_blog":
            result = self.generate_asset_via_registry(
                "generate_blog_post",
                topic=params.get("topic", "general"),
                keywords=params.get("keywords", ["blog", "content"]),
                tone=params.get("tone", "professional"),
                length=params.get("length", "medium"),
            )
            return {
                "success": result.get("success", False),
                "revenue": revenue,
                "costs": 0.0,
                "action": action,
                "details": result,
            }

        if action == "generate_ebook":
            result = self.generate_asset_via_registry(
                "generate_ebook_outline",
                topic=params.get("topic", "Untitled Ebook"),
                chapters=params.get("chapters", 5),
            )
            return {
                "success": result.get("success", False),
                "revenue": revenue,
                "costs": 0.0,
                "action": action,
                "details": result,
            }

        if action == "generate_social":
            result = self.generate_asset_via_registry(
                "generate_twitter_thread",
                topic=params.get("topic", "Check this out"),
                tweets=params.get("tweets", 5),
            )
            return {
                "success": result.get("success", False),
                "revenue": revenue,
                "costs": 0.0,
                "action": action,
                "details": result,
            }

        if action == "publish_to_medium":
            return self._publish_to_medium(params, revenue)

        if action == "publish_to_substack":
            return self._publish_to_substack(params, revenue)

        if action == "screenshot_review":
            return self._screenshot_review(params, revenue)

        return {
            "success": False,
            "revenue": 0.0,
            "costs": 0.0,
            "error": f"Unknown action: {action}",
        }

    def get_default_interval(self) -> int:
        """Return default cycle interval in seconds (5 minutes)."""
        return 300

    # ------------------------------------------------------------------
    # Publish helpers
    # ------------------------------------------------------------------

    def _publish_to_medium(self, params: Dict[str, Any], revenue: float) -> dict:
        """Open Chrome, navigate to Medium, and simulate a new story post."""
        try:
            self.browser.open_chrome(url="https://medium.com/new-story", new_window=False)
            time.sleep(3.0)

            # Title field (heuristic coordinates ~ upper-middle)
            self.browser.fill_form_field(0.35, 0.18, params.get("title", "Auto Post"))
            time.sleep(0.5)

            # Body field (click below title)
            self.browser.fill_form_field(0.35, 0.28, params.get("body", "Generated body."))
            time.sleep(0.5)

            # Simulate publish flow: click "Publish" (top-right heuristic)
            self.browser.win_click(0.88, 0.12)
            time.sleep(1.0)

            # Confirm publish in modal (center heuristic)
            self.browser.win_click(0.50, 0.55)
            time.sleep(2.0)

            return {
                "success": True,
                "revenue": revenue,
                "costs": 0.0,
                "platform": "medium",
                "title": params.get("title"),
            }
        except Exception as e:
            return {
                "success": False,
                "revenue": 0.0,
                "costs": 0.0,
                "error": str(e),
            }

    def _publish_to_substack(self, params: Dict[str, Any], revenue: float) -> dict:
        """Open Chrome, navigate to Substack, and simulate a new post."""
        try:
            self.browser.open_chrome(
                url="https://substack.com/home?action=new-post", new_window=False
            )
            time.sleep(3.5)

            # Substack title input (heuristic top area)
            self.browser.fill_form_field(0.30, 0.16, params.get("title", "Auto Post"))
            time.sleep(0.5)

            # Body paragraph (heuristic below title)
            self.browser.fill_form_field(0.30, 0.26, params.get("body", "Generated body."))
            time.sleep(0.5)

            # Click Continue / Publish (top-right heuristic)
            self.browser.win_click(0.90, 0.14)
            time.sleep(1.0)

            # Confirm send/publish (center modal heuristic)
            self.browser.win_click(0.50, 0.60)
            time.sleep(2.0)

            return {
                "success": True,
                "revenue": revenue,
                "costs": 0.0,
                "platform": "substack",
                "title": params.get("title"),
            }
        except Exception as e:
            return {
                "success": False,
                "revenue": 0.0,
                "costs": 0.0,
                "error": str(e),
            }

    def _screenshot_review(self, params: Dict[str, Any], revenue: float) -> dict:
        """Capture a screenshot and return a basic description."""
        try:
            state = self.browser.screenshot(filename=f"content_review_{int(time.time())}.png")
            description = (
                f"Screenshot captured. "
                f"Loading detected: {state.loading}. "
                f"Path: {state.screenshot_path}."
            )
            return {
                "success": True,
                "revenue": revenue,
                "costs": 0.0,
                "description": description,
                "screenshot_path": state.screenshot_path,
            }
        except Exception as e:
            return {
                "success": False,
                "revenue": 0.0,
                "costs": 0.0,
                "error": str(e),
            }
