"""
Base Business Agent for the Monetization Swarm.
All business agents inherit from this. Provides:
- Auto-decision making (AUTOPILOT tier)
- Revenue tracking per agent
- Vault persistence
- Tool execution via the business tool registry
"""

import asyncio
import json
import os
import time
import uuid
from abc import abstractmethod
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Any, Dict, List, Optional, Callable

from core.model_router import ModelRouter
from core.business_tools.registry import BusinessToolRegistry


@dataclass
class BusinessDecision:
    """A decision made by a business agent with full audit trail."""
    decision_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    agent_name: str = ""
    decision_type: str = ""  # e.g., 'price_change', 'create_listing', 'send_outreach'
    rationale: str = ""
    action_payload: Dict[str, Any] = field(default_factory=dict)
    estimated_revenue_impact: float = 0.0
    risk_score: float = 0.0  # 0.0 - 1.0
    confidence: float = 0.0  # 0.0 - 1.0
    status: str = "pending"  # pending, approved, rejected, executed, failed
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    result_summary: str = ""
    actual_revenue: float = 0.0


@dataclass
class AgentRevenueLedger:
    """Tracks all revenue generated by this agent."""
    agent_name: str = ""
    lifetime_revenue: float = 0.0
    lifetime_costs: float = 0.0
    decisions_made: int = 0
    decisions_executed: int = 0
    active_campaigns: List[str] = field(default_factory=list)
    daily_history: List[Dict[str, float]] = field(default_factory=list)


class BaseBusinessAgent:
    """
    Base class for all monetization swarm agents.
    
    Every business agent can:
    1. Run autonomously in a loop (AUTOPILOT tier)
    2. Make decisions with confidence/risk scoring
    3. Execute tools via BusinessToolRegistry
    4. Track its own revenue and costs
    5. Persist state to the unified business vault
    """

    def __init__(
        self,
        name: str,
        description: str,
        model_router: ModelRouter,
        autonomy_tier: str = "AUTOPILOT",
        decision_callback: Optional[Callable[[BusinessDecision], asyncio.Future]] = None,
    ):
        self.name = name
        self.description = description
        self.model_router = model_router
        self.autonomy_tier = autonomy_tier  # DEFAULT, OVERRIDE, AUTOPILOT
        self.decision_callback = decision_callback
        self.tools = BusinessToolRegistry()
        self.ledger = AgentRevenueLedger(agent_name=name)
        self.decisions: List[BusinessDecision] = []
        self.running = False
        self.task: Optional[asyncio.Task] = None
        self.vault_path = os.path.join("tools", "saved_sessions", f"agent_{name}_vault.json")
        self._load_vault()

    # ── Lifecycle ─────────────────────────────────────────────────────────

    async def start(self, interval_seconds: int = 300):
        """Start the autonomous business loop."""
        self.running = True
        self.task = asyncio.create_task(self._run_loop(interval_seconds))
        return self.task

    async def stop(self):
        """Stop the autonomous loop gracefully."""
        self.running = False
        if self.task:
            self.task.cancel()
            try:
                await self.task
            except asyncio.CancelledError:
                pass
        self._save_vault()

    async def _run_loop(self, interval: int):
        """Main autonomous loop: perceive → decide → act → learn."""
        while self.running:
            try:
                await self.cycle()
            except Exception as e:
                print(f"[{self.name}] Cycle error: {e}")
            await asyncio.sleep(interval)

    async def cycle(self):
        """
        One full business cycle:
        1. Perceive: gather data / market signals
        2. Decide: use LLM to decide what to do
        3. Act: execute tools
        4. Learn: update ledger & save vault
        """
        perception = await self.perceive()
        decision = await self.decide(perception)
        if decision and decision.status == "pending":
            if self.autonomy_tier == "AUTOPILOT" and decision.confidence > 0.7 and decision.risk_score < 0.5:
                decision.status = "approved"
            elif self.decision_callback:
                decision = await self.decision_callback(decision)
            else:
                decision.status = "approved"  # Default to auto-approve if no callback

            if decision.status == "approved":
                await self.execute(decision)
        self._save_vault()

    # ── Abstract hooks ────────────────────────────────────────────────────

    @abstractmethod
    async def perceive(self) -> Dict[str, Any]:
        """Gather market data, signals, or internal state. Return a dict of observations."""
        ...

    @abstractmethod
    async def decide(self, perception: Dict[str, Any]) -> Optional[BusinessDecision]:
        """Given perceptions, decide whether to act. Return a BusinessDecision or None."""
        ...

    @abstractmethod
    async def execute(self, decision: BusinessDecision):
        """Execute the approved decision using tools. Update decision with results."""
        ...

    # ── Shared utilities ──────────────────────────────────────────────────

    async def llm_decide(
        self,
        system_prompt: str,
        user_prompt: str,
        json_schema: Optional[Dict] = None,
    ) -> Dict[str, Any]:
        """Ask the LLM to make a structured decision."""
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]
        text = await self.model_router.chat(
            messages=messages,
            temperature=0.2,
        )
        # Try to parse JSON from the response
        try:
            import re
            json_match = re.search(r'\{.*\}', text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group())
            return {"raw": text}
        except Exception:
            return {"raw": text, "error": "json_parse_failed"}

    def log_decision(self, decision: BusinessDecision):
        """Record a decision and update the ledger."""
        self.decisions.append(decision)
        self.ledger.decisions_made += 1
        if decision.status == "executed":
            self.ledger.decisions_executed += 1
            self.ledger.lifetime_revenue += decision.actual_revenue

    def _load_vault(self):
        """Load persisted agent state."""
        if os.path.exists(self.vault_path):
            try:
                with open(self.vault_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                self.ledger = AgentRevenueLedger(**data.get("ledger", {}))
                self.decisions = [BusinessDecision(**d) for d in data.get("decisions", [])]
            except Exception:
                pass

    def _save_vault(self):
        """Persist agent state to disk."""
        os.makedirs(os.path.dirname(self.vault_path), exist_ok=True)
        data = {
            "agent_name": self.name,
            "updated_at": datetime.utcnow().isoformat(),
            "ledger": asdict(self.ledger),
            "decisions": [asdict(d) for d in self.decisions[-500:]],  # Keep last 500
        }
        with open(self.vault_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, default=str)

    def get_status(self) -> Dict[str, Any]:
        """Return current agent status for dashboard display."""
        return {
            "name": self.name,
            "description": self.description,
            "running": self.running,
            "autonomy_tier": self.autonomy_tier,
            "ledger": asdict(self.ledger),
            "recent_decisions": [asdict(d) for d in self.decisions[-10:]],
            "net_profit": self.ledger.lifetime_revenue - self.ledger.lifetime_costs,
        }
