#!/usr/bin/env python3
"""
ingest_account_keys.py
======================
Reads content/account_setup/PASTE_KEYS_HERE.env and integrates the keys
into swarm-backend/business_config.json and .env files.

Usage:
    python tools/ingest_account_keys.py
    python tools/ingest_account_keys.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

ENV_FILE = Path("content/account_setup/PASTE_KEYS_HERE.env")
CONFIG_FILE = Path("swarm-backend/business_config.json")
DOTENV_FILE = Path(".env")


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse a simple KEY=VALUE env file, skipping comments and blanks."""
    data: dict[str, str] = {}
    if not path.exists():
        print(f"[WARN] {path} not found")
        return data
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, val = line.partition("=")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            data[key] = val
    return data


def is_placeholder(val: str) -> bool:
    """Return True if the value looks like a placeholder."""
    if not val:
        return True
    placeholders = [
        "paste_here",
        "leave_blank",
        "your_",
        "...",
        "PASTE",
        "YOUR-",
        "YOUR_",
    ]
    lower = val.lower()
    return any(p in lower for p in placeholders)


def load_business_config() -> dict:
    if CONFIG_FILE.exists():
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except json.JSONDecodeError:
            pass
    return {
        "_comment": "Auto-generated by ingest_account_keys.py",
        "stripe": {},
        "printify": {},
        "etsy": {},
        "shopify": {},
        "openai": {},
        "claude": {},
        "gemini": {},
        "email": {},
        "affiliate": {},
        "content": {},
        "swarm_settings": {},
    }


def save_business_config(config: dict) -> None:
    CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)
        f.write("\n")


def update_config_from_env(config: dict, env: dict[str, str]) -> tuple[dict, list[str]]:
    """Merge env keys into business_config. Returns updated config + list of changes."""
    changes: list[str] = []

    # ClickBank → content.clickbank
    cb_nick = env.get("CLICKBANK_ACCOUNT_NICKNAME", "")
    if cb_nick and not is_placeholder(cb_nick):
        config.setdefault("content", {})
        config["content"]["clickbank_nickname"] = cb_nick
        changes.append(f"clickbank_nickname = {cb_nick}")

    cb_tracking = env.get("CLICKBANK_TRACKING_IDS", "")
    if cb_tracking and not is_placeholder(cb_tracking):
        config.setdefault("content", {})
        config["content"]["clickbank_tracking_ids"] = cb_tracking
        changes.append(f"clickbank_tracking_ids = {cb_tracking}")

    # Medium → content.medium
    medium_token = env.get("MEDIUM_API_TOKEN", "")
    if medium_token and not is_placeholder(medium_token):
        config.setdefault("content", {})
        config["content"]["medium_api_token"] = medium_token
        changes.append("medium_api_token = <set>")

    medium_user = env.get("MEDIUM_USER_ID", "")
    if medium_user and not is_placeholder(medium_user):
        config.setdefault("content", {})
        config["content"]["medium_user_id"] = medium_user
        changes.append(f"medium_user_id = {medium_user}")

    # Substack → content.substack
    substack_url = env.get("SUBSTACK_URL", "")
    if substack_url and not is_placeholder(substack_url):
        config.setdefault("content", {})
        config["content"]["substack_url"] = substack_url
        changes.append(f"substack_url = {substack_url}")

    substack_name = env.get("SUBSTACK_PUBLICATION_NAME", "")
    if substack_name and not is_placeholder(substack_name):
        config.setdefault("content", {})
        config["content"]["substack_publication_name"] = substack_name
        changes.append(f"substack_publication_name = {substack_name}")

    substack_email = env.get("SUBSTACK_FROM_EMAIL", "")
    if substack_email and not is_placeholder(substack_email):
        config.setdefault("content", {})
        config["content"]["substack_from_email"] = substack_email
        changes.append(f"substack_from_email = {substack_email}")

    # Amazon → affiliate.amazon_associates_tag
    amazon_tag = env.get("AMAZON_ASSOCIATES_TAG", "")
    if amazon_tag and not is_placeholder(amazon_tag):
        config.setdefault("affiliate", {})
        config["affiliate"]["amazon_associates_tag"] = amazon_tag
        changes.append(f"amazon_associates_tag = {amazon_tag}")

    # Stripe
    stripe_pub = env.get("STRIPE_PUBLISHABLE_KEY", "")
    if stripe_pub and not is_placeholder(stripe_pub):
        config.setdefault("stripe", {})
        config["stripe"]["publishable_key"] = stripe_pub
        changes.append("stripe_publishable_key = <set>")

    stripe_sec = env.get("STRIPE_SECRET_KEY", "")
    if stripe_sec and not is_placeholder(stripe_sec):
        config.setdefault("stripe", {})
        config["stripe"]["secret_key"] = stripe_sec
        changes.append("stripe_secret_key = <set>")

    # SMTP → email
    smtp_host = env.get("SMTP_HOST", "")
    if smtp_host and not is_placeholder(smtp_host):
        config.setdefault("email", {})
        config["email"]["smtp_host"] = smtp_host
        changes.append(f"smtp_host = {smtp_host}")

    smtp_port = env.get("SMTP_PORT", "")
    if smtp_port and not is_placeholder(smtp_port):
        config.setdefault("email", {})
        config["email"]["smtp_port"] = int(smtp_port) if smtp_port.isdigit() else smtp_port
        changes.append(f"smtp_port = {smtp_port}")

    smtp_user = env.get("SMTP_USER", "")
    if smtp_user and not is_placeholder(smtp_user):
        config.setdefault("email", {})
        config["email"]["username"] = smtp_user
        changes.append(f"smtp_user = {smtp_user}")

    smtp_pass = env.get("SMTP_PASS", "")
    if smtp_pass and not is_placeholder(smtp_pass):
        config.setdefault("email", {})
        config["email"]["password"] = smtp_pass
        changes.append("smtp_password = <set>")

    return config, changes


def update_dotenv(env: dict[str, str], dry_run: bool) -> list[str]:
    """Append missing keys to .env file. Returns list of additions."""
    additions: list[str] = []
    lines: list[str] = []

    if DOTENV_FILE.exists():
        lines = DOTENV_FILE.read_text(encoding="utf-8").splitlines()

    existing_keys = set()
    for line in lines:
        if "=" in line and not line.strip().startswith("#"):
            k = line.split("=")[0].strip()
            existing_keys.add(k)

    key_mapping = {
        "MEDIUM_API_TOKEN": None,
        "SUBSTACK_URL": None,
        "CLICKBANK_ACCOUNT_NICKNAME": None,
        "CLICKBANK_DEVELOPER_KEY": None,
        "CLICKBANK_API_SECRET": None,
        "AMAZON_ASSOCIATES_TAG": None,
        "STRIPE_PUBLISHABLE_KEY": None,
        "STRIPE_SECRET_KEY": None,
        "SMTP_HOST": None,
        "SMTP_PORT": None,
        "SMTP_USER": None,
        "SMTP_PASS": None,
    }

    new_lines: list[str] = []
    for k, _ in key_mapping.items():
        v = env.get(k, "")
        if v and not is_placeholder(v) and k not in existing_keys:
            new_lines.append(f'{k}="{v}"')
            additions.append(k)

    if new_lines and not dry_run:
        with open(DOTENV_FILE, "a", encoding="utf-8") as f:
            f.write("\n# --- Auto-ingested from account_setup ---\n")
            for line in new_lines:
                f.write(line + "\n")

    return additions


def main():
    parser = argparse.ArgumentParser(description="Ingest account keys into swarm config")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing")
    args = parser.parse_args()

    print("=" * 60)
    print("ACCOUNT KEY INGESTOR")
    print("=" * 60)

    env = parse_env_file(ENV_FILE)
    config = load_business_config()

    config, config_changes = update_config_from_env(config, env)
    dotenv_additions = update_dotenv(env, args.dry_run)

    print(f"\nSource: {ENV_FILE}")
    print(f"Config target: {CONFIG_FILE}")
    print(f".env target: {DOTENV_FILE}")

    if config_changes:
        print(f"\nConfig changes ({len(config_changes)}):")
        for c in config_changes:
            print(f"  + {c}")
    else:
        print("\nNo new config keys to ingest (all blank or placeholder).")

    if dotenv_additions:
        print(f"\n.env additions ({len(dotenv_additions)}):")
        for a in dotenv_additions:
            print(f"  + {a}")
    else:
        print("\nNo new .env keys to append.")

    if args.dry_run:
        print("\n[DRY RUN] No files modified.")
    else:
        save_business_config(config)
        print(f"\n[OK] Config saved to {CONFIG_FILE}")
        if dotenv_additions:
            print(f"[OK] Keys appended to {DOTENV_FILE}")

    print("=" * 60)


if __name__ == "__main__":
    main()
